config/routes.rb
Rails.application.routes.draw do
  get 'setup/index'
  match '/setup', to: 'setup#index', via: [:get, :post]

  resources :people
  get 'admin', to: 'visitor_log#index'
  get 'visitor_log/index'
  get '/visitor_log', to: 'visitor_log#index'
  get 'visitor_log/:action', controller: 'visitor_log'
  resources :companies
  resources :reasons

  devise_for :users
  resources :employees, path: :persons, except: [:edit] do
    member do
      get 'log_in'
    end
    get 'home/index', as: 'home'
  end

  resources :users, only: [:index, :show, :destroy] do
    collection do
      match 'recently_connected', via: [:post, :get]
      match 'active', via: [:post, :get]
      match 'audit', via: [ :get]
    end
    member do
      get 'require_change_password'
      get 'restore'
      get 'lock'
      get 'unlock'
      put 'change_password'
      put 'change_basic_info'
      put 'attachments'
      post 'image_upload'
      get 'remove_image'
    end


  end


  root to: 'welcome#visitors'

  match '/create_visitor', to: 'welcome#create_visitor', via: [:get, :post]

  get '/update_visitor', to: 'welcome#update_visitor'
  post '/update_visitor_visit', to: 'welcome#update_visitor_visit'
  post '/get_visitor_info', to: 'welcome#get_visitor_info'
  get '/visitors', to: 'welcome#visitors'
  get '/visitor_bye', to: 'welcome#visitor_bye'
  match '/visitor_signout', to: 'welcome#visitor_signout', via: [:get, :post]
  match '/check_visitor', to: 'welcome#check_visitor', via: [:get, :post]
  get '/visitor_sign_form', to: 'welcome#visitor_sign_form'
  get '/visitor_badge', to: 'welcome#visitor_badge'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :admin_login_pages, only: :index do
    collection do
      post :update
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string(255)
#  locked_at              :datetime
#  full_name              :string(255)      default("")
#  admin                  :boolean          default(FALSE)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  avatar                 :string(255)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def self.current=(user)
    RequestStore.store[:current_user] = user
  end

  def self.current
    RequestStore.store[:current_user] ||= User.new
  end

  def profile_image
    if avatar.thumb.url
      avatar.thumb.url
    else
      'male.png'
    end
  end

  def self.safe_attributes
    [:full_name, :state, :email, :role_id, :time_zone,:password_confirmation,  :password]
  end

  def name; full_name; end


  mount_uploader :avatar, AvatarUploader
end

app/controllers/users_controller.rb
class UsersController < BaseController
  before_action  :authenticate_user!
  before_action :find_user, except: [:restore, :index, :active, :audit, :recently_connected]

  # before_action :require_admin, only: [:index, :destroy, :active]
  # before_action :authorize, except: [:index, :destroy, :active, :search_users,
  #                                    :image_upload, :remove_image,
  #                                    :recently_connected]

  def recently_connected
    respond_to do |format|
      format.js{
        @recently_connected = User.
            recently_active.
            includes(:core_demographic).
            where.not(id: current_user.id )
      }
    end
  end

  def search_users
    q = params[:q]
    respond_to do |format|
      format.js{
        @recently_connected = User.
            where('login like ? OR email like ?', "#{q}%",  "#{q}%").
            includes(:core_demographic).
            where.not(id: current_user.id )
      }
    end
  end


  def image_upload
    @user.avatar = params[:images]
    @user.save(validate: false)
    render 'uploader/image_upload'
  end

  def remove_image
    @user.remove_avatar!
    @user.save
    render 'uploader/remove_image'
  end



  # authorized by admin
  def index
    respond_to do |format|
      format.html{}
      format.json{
        options = Hash.new
        render json: UserDatatable.new(view_context,options)
      }
    end
  end

  def active
    if request.post?
      user = User.find params[:user_id]
      user.last_seen_at = 1.year.ago
      user.save
    end
    @users = User.recently_active.
        includes(:core_demographic).
        references(:core_demographic)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def destroy
    @user.destroy
    flash[:notice] = I18n.t('notice_successful_delete')
    redirect_to :back
  end

  # authorized by manage roles





  def audit
    @users = User.includes(:core_demographic).
        references(:core_demographic)
  end

  def restore
    u = User.unscoped.find params[:id]
    u.restore
    u.save
    flash[:notice] = 'User restored'
    redirect_to :back
  end

  def lock
    u = User.unscoped.find params[:id]
    u.failed_attempts = Setting['maximum_attempts'].to_i
    u.locked_at = Time.now
    u.save
    flash[:notice] = 'User locked'
    redirect_to :back
  end

  def unlock
    u = User.unscoped.find params[:id]
    u.failed_attempts = 0
    u.locked_at = nil
    u.save
    flash[:notice] = 'User unlocked'
    redirect_to :back
  end



  def show
    # @profile       = @user.profile
  end

  def attachments
    @user.update(params.require(:user).permit(user_attachments_attributes: [Attachment.safe_attributes]))
    @user.save
    redirect_to user_path(@user)
  end


  def change_password
    if params[:user][:password] == params[:user][:password_confirmation]
      if @user.update(password: params[:user][:password])
        flash[:notice] = I18n.t('devise.passwords.updated_not_active')
      else
        flash[:error] = @user.errors.full_messages.join('<br/>')
      end

    else
      flash[:error] = 'Password not matched'
    end
    redirect_to user_path(@user)
  end


  def change_basic_info
    if @user.update(params.require(:user).permit(User.safe_attributes + [:admin]))
      flash[:notice] = I18n.t('notice_successful_update')
    else
      flash[:error] = I18n.t('error_update')
    end
    redirect_to user_path(@user)
  end




  def require_change_password
    @user.password_changed_at = 181.days.ago
    @user.save(validate: false)
    flash[:notice] = 'User require changing password next login'
    redirect_to :back
  end

  private

  def find_user
    @user = User.find params[:id]
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def authorize
    render_403 unless User.current.can?(:manage_roles)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def password_min
    User.password_length.min
  end

  def password_max
    User.password_length.max
  end

  def user_admin_show_page
    tabs = [
        {:name => 'user_basic', :partial => 'users/shared/user_basic_information', :label => :user_basic_information},
        {:name => 'password', :partial => 'users/shared/password', :label => :password}
     ]
    tabs
  end

end

app/views/users/_active.html.erb
<table class="table  table-responsive" id="users_table">
  <thead>
  <tr>
    <th><%= t :login %></th>
    <th><%= t :email %></th>
    <th> <%= t('profile.first_name') %> </th>

    <th> <%= t('profile.middle_name') %> </th>
    <th> <%= t('profile.last_name') %> </th>
    <th> <%= t('role') %> </th>

    <th> <%= t('status') %> </th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.first_name %></td>

    <td><%= user.middle_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.role.to_s %></td>

    <td><%= user.active? %></td>
    <td><%= link_to 'Sign out', active_users_path(user_id: user.id), method: 'post' %></td>
  </tr>
  <% end %>
  </tbody>
</table>

<script>
  $(document).ready(function(){
    initDataTable('users_table')
  })
</script>

app/views/users/_audit.html.erb
<table class="table  table-responsive" id="users_table">
  <thead>
  <tr>
    <th><%= t :login %></th>
    <th><%= t :email %></th>
    <th> Last seen at </th>
    <th> Sign in count </th>
    <th> Last Sign in at</th>
    <th> Last Sign in IP</th>
    <th> Failed Attempts</th>
    <th> Locked at </th>
    <th> Password changed At </th>
  </tr>
  </thead>


  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= format_date_time user.last_activity_at %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= format_date_time user.last_sign_in_at %></td>
        <td><%=  user.last_sign_in_ip %></td>
        <td><%=  user.failed_attempts %></td>
        <td><%=  format_date_time user.locked_at %></td>
        <td><%=  format_date_time user.password_changed_at %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<script>
  $(document).ready(function(){
    initDataTable('users_table')
  })
</script>

app/views/users/_list.html.erb
<table style="width: 100%" class="table  table-responsive display responsive nowrap" id="users_table">
  <thead>
  <tr>
    <th>#</th>
    <th><%= t :login %></th>
    <th><%= t :email %></th>



  </tr>
  </thead>

  <tbody>
  <% User.all.each do |user| %>
  <tr>
    <td><%= link_to user.id, user %></td>
    <td><%= user.email %></td>
    <td><%= user.name %></td>
  </tr>
  <% end %>

  </tbody>
</table>

<script>
  $(document).ready(function(){
    var table = $('#users_table').DataTable({

    })
  } );
</script>

app/views/users/_password.html.erb
<%= form_for(user, url: change_password_user_path(user), html: { method: :put, class: 'form-horizontal', id: 'smart-form-register' }) do |f| %>

    <fieldset>
      <legend></legend>

      <div class="form-group">
        <label class="col-md-2 control-label">Password</label>
        <div class="col-md-9">
          <%= f.password_field :password, autocomplete: "off", placeholder: 'Password' , class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">Password confirmation</label>
        <div class="col-md-9">
          <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Password confirmation' , class: 'form-control' %>
        </div>
      </div>

      <div class="form-group" >
        <div class="col-md-11">
          <%= f.submit "Update", class: 'btn btn-success pull-right' %>
        </div>
      </div>
    </fieldset>
<% end %>
<script>
  // Validation
  $(function() {
    runAllForms();
    // Validation
    $("#smart-form-register").validate({

      // Rules for form validation
      rules : {
        "user[password]" : {
          required : true,
          <% if password_min %>
          minlength : <%= password_min %>,
          <% end %>
          <% if password_max %>
          maxlength : <%= password_max %>
          <% end %>
        },
        "user[password_confirmation]" : {
          required : true,
          <% if password_min%>
          minlength : <%= password_min %>,
          <% end %>
          <% if password_max %>
          maxlength : <%= password_max %>,
          <% end %>
          equalTo : '#user_password'
        }
      },

      // Messages for form validation
      messages : {
        password : {
          required : 'Please enter your password'
        },
        passwordConfirm : {
          required : 'Please enter your password one more time',
          equalTo : 'Please enter the same password as above'
        }
      },
      // Do not change code below
      errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
      }
    });

  });
</script>

app/views/users/_recently_connected.html.erb
<% @recently_connected.each do |user | %>
    <a href="<%= "/chat_rooms/create_or_find?user_id=#{user.id}" %>" class="usr"
       data-chat-id="cha1"
       data-chat-fname="<%= user.first_name || user.login %>"
       data-chat-lname="<%= user.last_name %>"
       data-chat-status="online"
       data-chat-alertmsg=""
       data-chat-alertshow="true"
       data-rel="popover-hover"
       data-placement="right"
       data-html="true"
       data-content="
											<div class='usr-card'>
												<%= "#{avatar(user)}" %>
												<div class='usr-card-content'>
													<h3><%= user.login %></h3>
													<p></p>
												</div>
											</div>
										"
    >
      <i></i><%= user.profile_name.strip.presence || user.login %>
    </a>
<% end %>

app/views/users/_user_attachments.html.erb
<%= form_for(user, url: attachments_user_path(user), html: { method: :put, class: 'form-horizontal', id: 'smart-form-register' }) do |f| %>

    <div class="form-group">
      <div class="col-md-12">
        <%= f.label t(:attachments) , class: 'col-md-2 control-label' %>
      </div>
      <%= f.simple_fields_for :user_attachments do |attachment| %>
          <%= render 'attachments/attachment_show', :f => attachment %>
      <% end %>
      <div id="attachment_fields" class="col-xs-2 margin-top-10 " style="padding-right: 2px;" >
        <%= link_to_add_association 'add file', f, :user_attachments, class: 'btn btn-success pull-right', partial: 'attachments/attachment_fields' %>
      </div>
    </div>

    <div class="form-group" >
      <div class="col-md-11">
        <%= f.submit "Save", class: 'btn btn-success pull-right' %>
      </div>
    </div>
<% end %>

app/views/users/_user_basic_info.html.erb
<%= form_for(user, url: change_basic_info_user_path(user), html: { method: :put, class: 'form-horizontal', id: 'smart-form-register' }) do |f| %>

    <fieldset>
      <legend></legend>


      <div class="form-group">
        <label class="col-md-2 control-label">Email</label>
        <div class="col-md-9">
          <%= f.email_field :email, placeholder: 'Email' , class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">Administrator</label>
        <div class="col-md-9">
          <%= f.check_box :admin %>
        </div>
      </div>



      <div class="form-group" >
        <div class="col-md-11">
          <%= f.submit "Update", class: 'btn btn-success pull-right' %>
        </div>
      </div>
    </fieldset>
<% end %>
<script>
  // Validation
  $(function() {
    runAllForms();
    // Validation
    $("#smart-form-register").validate({

      // Rules for form validation
      rules : {
        "user[login]" : {
          required : true
        },
        "user[email]" : {
          required : true
        }
      },
      // Do not change code below
      errorPlacement : function(error, element) {
        error.insertAfter(element.parent());
      }
    });

  });
</script>

app/views/users/active.html.erb
<section id="widget-grid" class="users_list">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'active',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     wid_id: 'users',
                     wid_title: t(:users)
                 } %>
    </article>
  </div>
</section>

app/views/users/audit.html.erb
<section id="widget-grid" class="users_list">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'audit',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     wid_id: 'users',
                     wid_title: 'Audit users'
                 } %>
    </article>
  </div>
</section>

app/views/users/index.html.erb
<div class="module-title">
  <h2 class='module-title-text'>USERS</h2>
</div>

<section id="widget-grid" class="users_list">
  <div class="row" style="margin-bottom: 10px">
    <div class="col-md-12 ">
      <div class="pull-right">
        <%= show_button(new_employee_path, 'New user', 'plus', 'primary') %>
       </div>
    </div>
  </div>
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render partial: 'list',
                 layout: 'shared/smart_widget_wrapper',
                 locals: {
                     wid_id: 'users',
                     wid_title: ' '
                 } %>
    </article>
  </div>
</section>

app/views/users/recently_connected.js.erb
$('#user_connected').html("<%= escape_javascript(render partial: 'users/recently_connected') %>")

app/views/users/search_users.js.erb
$('#user_connected').html("<%= escape_javascript(render partial: 'users/recently_connected') %>")

app/views/users/show.html.erb
<div class="row" style="margin-bottom: 10px">
  <div class="col-md-12 ">
    <div class="pull-right">
      <%= show_button(users_path, 'Cancel', 'reply', 'primary') %>
    </div>
  </div>
</div>

<h1><%= @user.name %></h1>
<%= render_tabs user_admin_show_page %>