config/routes.rb
Rails.application.routes.draw do
  get 'setup/index'
  match '/setup', to: 'setup#index', via: [:get, :post]

  resources :people
  get 'admin', to: 'visitor_log#index'
  get 'visitor_log/index'
  get '/visitor_log', to: 'visitor_log#index'
  get 'visitor_log/:action', controller: 'visitor_log'
  resources :companies
  resources :reasons

  devise_for :users
  resources :employees, path: :persons, except: [:edit] do
    member do
      get 'log_in'
    end
    get 'home/index', as: 'home'
  end

  resources :users, only: [:index, :show, :destroy] do
    collection do
      match 'recently_connected', via: [:post, :get]
      match 'active', via: [:post, :get]
      match 'audit', via: [ :get]
    end
    member do
      get 'require_change_password'
      get 'restore'
      get 'lock'
      get 'unlock'
      put 'change_password'
      put 'change_basic_info'
      put 'attachments'
      post 'image_upload'
      get 'remove_image'
    end


  end


  root to: 'welcome#visitors'

  match '/create_visitor', to: 'welcome#create_visitor', via: [:get, :post]

  get '/update_visitor', to: 'welcome#update_visitor'
  post '/update_visitor_visit', to: 'welcome#update_visitor_visit'
  post '/get_visitor_info', to: 'welcome#get_visitor_info'
  get '/visitors', to: 'welcome#visitors'
  get '/visitor_bye', to: 'welcome#visitor_bye'
  match '/visitor_signout', to: 'welcome#visitor_signout', via: [:get, :post]
  match '/check_visitor', to: 'welcome#check_visitor', via: [:get, :post]
  get '/visitor_sign_form', to: 'welcome#visitor_sign_form'
  get '/visitor_badge', to: 'welcome#visitor_badge'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :admin_login_pages, only: :index do
    collection do
      post :update
    end
  end
end

app/views/shared/_footer.html.erb
<style>
  .dropdown-menu{border-radius:0;border-bottom:2px solid #ADADAD;background:#FDDFB3}

</style>
<!--

<div class="row">
  <div class="col-xs-4">
    <span class="txt-color-white">mCMS <span class="hidden-xs"> – MicroHealth </span> © 2017</span>
  </div>

  <div class="col-xs-4">
      <span class="txt-color-white">
      This program is licensed under GPL v3 <br/>
      <a href="https://www.gnu.org/licenses/gpl-3.0.html" target="_blank">https://www.gnu.org/licenses/gpl-3.0.html</a>
    </span>
  </div>

  <div class="col-xs-3">
      <span class="txt-color-white">
        Please send your feedback <br/>
        <A HREF="mailto:feedback@microhealthllc.com">feedback@microhealthllc.com</A>
      </span>
  </div>

</div>

-->

app/views/shared/_head.html.erb
<head>
  <meta charset="utf-8">
  <!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">-->

  <title> <%= Setting['application_name'] %> </title>
  <meta name="description" content="">
  <meta name="author" content="">

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <!-- Basic Styles -->


  <%= stylesheet_link_tag  'admin/application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track'=> 'reload' %>

  <meta name="turbolinks-cache-control" content="no-cache">

  <%= csrf_meta_tags %>

  <style>
    body {
        font-size: 15px;    
    }

    .smart-style-5
    {
      background: url(/assets/glass.jpg) no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }

    .smart-style-3 #header {
      background-color: #dddddd;
      background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#dddddd), to(#dddddd));
      background-image: -webkit-linear-gradient(top, #dddddd, #dddddd);
      background-image: linear-gradient(to bottom, #dddddd, #dddddd);
    }

    .smart-style-3 .btn-header>:first-child>a {
      background-color: #DD7C37;
      background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#dd7c37), to(#dd7c37));
      background-image: -webkit-linear-gradient(top, #dd7c37, #dd7c37);
      background-image: linear-gradient(to bottom, #dd7c37, #dd7c37);
      color: #fff !important;
      border: 1px solid #dd7c37;
      text-shadow: none;
    }
   
    .smart-style-1 .btn-header>:first-child>a {
      background: #dd7c37;
      border: 1px solid #dd7c37;
      color: #fff !important;
      cursor: pointer !important;
    }

   
    h2 {
        font-size: 24px;
    }
    .form-control {
        font-size: 15px; 
    }

    .btn {
        font-size: 15px; 
    }

    .table thead tr {
        font-size: 14px; 
    }

    .dropdown-menu {
        min-width: 170px;
        font-size: 15px;
    }

    .login-info a span {
        font-size: 14px; 
    }
 
    abbr[title] {
      border-bottom: none;
      text-decoration: none;
    }

    .jarviswidget-color-blueLight>header {
      border-color:#a0aeb3 !important;background:#B2C8D6;
    }
   .jarviswidget>header h2 {
        font-size: 18px;
    }

    .jarviswidget>div {
        font-size: 15px;
    }

    .ui-tabs .ui-tabs-nav li a {
      background-color:#4D7484;color:#ffffff;border:none;box-shadow: none;
    }
    .ui-tabs .ui-tabs-nav li a:hover {
      border:none;background-color:#DBC2A4;color:#000000;box-shadow: none;
    }
    .ui-tabs .ui-tabs-nav li.ui-tabs-active:hover {
      background:#dd7c37;cursor:text;
    }
    .ui-tabs .ui-tabs-nav .ui-tabs-anchor {
      background-color:#4D7484;
    }
    .ui-tabs .ui-tabs-nav li.ui-tabs-active {
      margin-top: 4px;
      margin-bottom: 0;
      padding-bottom: 0;
    }
    .ui-tabs .ui-tabs-nav li.ui-tabs-active a {
      background-color:#dd7c37;color:#ffffff;border:none;margin-top: 0px !important;
      font-weight: 400; box-shadow: none;
    }
    .ui-state-active, .ui-widget-content .ui-state-active, .ui-widget-header .ui-state-active {
      background: #ffffff;
    }
    .jarviswidget-color-blueLight .nav-tabs li:not(.active) a {
        color: white !important;
    }
    .jarviswidget-color-blueLight .nav-tabs li a:hover {
        color: black !important;
    }  
    
   .ui-tabs .ui-tabs-nav {
    border: solid #dd7c37;
    border-width: 0 0 3px;
    border-radius: 0;
    background: 0 0;
    }
    .ui-tabs .ui-tabs-nav li a:hover, .ui-tabs .ui-tabs-nav li.ui-tabs-active:hover, .jarviswidget-color-blueLight .nav-tabs li a:hover {
      color:#000000;box-shadow: none;border:none;
    }
   
    .ui-tabs .ui-tabs-nav li {
      margin: 4px 1px 0 1px;
      border: none;
    }
    .ui-tabs .ui-tabs-nav li a {
      border: none;box-shadow: none;
    }


    nav ul li a, .smart-style-3 nav>ul>li>a, .smart-style-1 nav ul ul li>a {
        font-size: 15px; 
    }

    .page-footer span {
        font-size: 1.125em; 
    }

    div.dataTables_info {
        font-size: 14px; 
    }

    .pagination-sm>li>a {
        font-size: 14px; 
    }
    
    #logo-group>span {
        font-size: 24px; 
    }
    
   .ui-widget-content, .ui-widget.ui-widget-content {
     border: none;
    }
  </style>
  <!-- We recommend you use "your_style.css" to override SmartAdmin
       specific styles this will also ensure you retrain your customization with each SmartAdmin update.
  <link rel="stylesheet" type="text/css" media="screen" href="css/your_style.css"> -->

  <!-- FAVICONS -->
  <%= favicon_link_tag 'favicon.ico' %>


  <!-- Specifying a Webpage Icon for Web Clip

  <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">


</head>

app/views/shared/_header.html.erb
<header class='noprint' id="header">

  <div id="logo-group">

    <!-- PLACE YOUR LOGO HERE -->
    <span id="logo1" style="margin: 10px;"> <%= link_to "#{image_tag( "logo.png", alt: '', size: '30x30' )} #{Setting['application_name']}".html_safe , root_path %> </span>
    <!-- END LOGO PLACEHOLDER -->

  </div>
  <!-- end projects dropdown -->

  <!-- pulled right: nav area -->
  <div class="pull-right">

    <!-- collapse menu button -->
    <div id="hide-menu" class="noprint btn-header pull-right">
      <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
    </div>
    <!-- end collapse menu -->

    <!-- #MOBILE -->

    <!-- logout button -->
    <div id="logout" class="noprint btn-header transparent pull-right">
      <span>
        <% if user_signed_in? %>
            <%= link_to destroy_session_path(:user), title: 'Sign out', :method => :delete do %>
                <i class="fa fa-sign-out"></i>
            <% end %>
        <% else %>
            <%= link_to new_session_path(:user), title: "Sign In" do %>
                <i class="fa fa-sign-in"></i>
            <% end %>
        <% end %>
      </span>
    </div>
    <!-- end logout button -->

    <!-- search mobile button (this is hidden till mobile view port) -->
    <div id="search-mobile" class="noprint btn-header transparent pull-right">
      <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
    </div>
    <!-- end search mobile button -->


    <!-- fullscreen button -->
    <div id="fullscreen" class="noprint btn-header transparent pull-right">
      <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
    </div>

    <div id="logout" class="noprint btn-header transparent pull-right">
      <span>
        <% if user_signed_in? and session[:employee_id]%>
            <%= link_to "/persons/#{User.current.id}", title: "Log off from #{User.current.login}", :method => :delete do %>
                    <i class="fa fa-times-circle"></i>
            <% end %>
        <% end %>
      </span>
    </div>
    <!-- end fullscreen button -->

    <!-- end voice command -->

    <!-- end multiple lang -->

  </div>
  <!-- end pulled right: nav area -->

</header>

app/views/shared/_shortcuts.html.erb
<div class='noprint' id="shortcut">
  <ul>
    <% if user_signed_in? %>
        <% if (User.current == current_user) and !session[:employee_id] %>
            <li>
              <%= link_to edit_user_registration_path, class: 'jarvismetro-tile big-cubes selected bg-color-pinkDark' do %>
                  <i class="fa fa-user fa-4x"></i> <span>My Profile </span>
              <% end %>
            </li>

            <li>
              <%= link_to destroy_user_session_path, :method => :delete, class: 'jarvismetro-tile big-cubes selected bg-color-greenLight' do %>
                  <i class="fa fa-user fa-4x"></i> <span> Sign out </span>
              <% end %>
            </li>
        <% else %>
            <li>
              <%= link_to employee_path(User.current), :method => :delete, class: 'jarvismetro-tile big-cubes selected bg-color-greenLight' do %>
                  <i class="fa fa-user fa-4x"></i> <span> Sign out </span>
              <% end %>
            </li>
        <% end %>
    <% else %>
        <%= link_to new_user_session_path, class: 'jarvismetro-tile big-cubes selected bg-color-pinkDark' do %>
            <i class="fa fa-user fa-4x"></i> <span> Sign In </span>
        <% end %>

        <%= link_to new_registration_path(:user), class: 'jarvismetro-tile big-cubes selected bg-color-greenLight' do %>
            <i class="fa fa-user fa-4x"></i> <span> Register </span>
        <% end %>
    <% end %>
  </ul>
</div>

app/views/shared/_smart_widget_wrapper.html.erb
<div class="jarviswidget jarviswidget-color-blueLight" id="<%= wid_id %>" data-widget-deletebutton="false"  data-widget-sortable='false' data-widget-editbutton="false">
  <header>
    <h2><strong><%= wid_title %></strong> </h2>
  </header>
  <div>
    <div class="widget-body no-padding">
      <div class="row">
        <div class="col-xs-12" style="overflow: hidden" id="<%= wid_id %>_container">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tabs.html.erb
<script>
    function hashLinks() {
        $(".links a").prop("hash", location.hash.replace(/#tabs/,"#for"))
    }
    $( function() {
        $("#<%= tab_name %>").tabs({
            activate: function(event, ui) {
                hash = ui.newTab.find("[href]").prop("hash");
                history.pushState({}, '', hash);
                hashLinks()
            }
        });
    } );
</script>

<section id="widget-grid" class="show_tab">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="ui-tabs ui-widget ui-widget-content ui-corner-all" id="<%= tab_name %>">
        <ul class="nav-tabs ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
          <% tabs.each do |tab| -%>
              <li class="ui-state-default ui-corner-top">
                <a class="ui-tabs-anchor" id="link-tabs-modules" href="<%=  "#tabs-#{tab[:name] }" %>"><%= t(tab[:label]) %></a>
              </li>
          <% end -%>
        </ul>
        <% tabs.each_with_index do |tab, idx| -%>
            <div style="padding: 1em 0; display: <%= idx.zero? ? 'block' : 'none' %>" class="nav-tabs-div ui-tabs-panel ui-widget-content ui-corner-bottom" id="<%= "tabs-#{tab[:name]}" %>">
              <%= render partial: tab[:partial], :locals => {:tab => tab} %>
            </div>
        <% end -%>
      </div>
    </article>
  </div>
</section>
<style>
  .ui-widget-content a {
    color: #214e75;
  }
  a.btn{
    color: white
  }
</style>