config/routes.rb
Rails.application.routes.draw do
  get 'setup/index'
  match '/setup', to: 'setup#index', via: [:get, :post]

  resources :people
  get 'admin', to: 'visitor_log#index'
  get 'visitor_log/index'
  get '/visitor_log', to: 'visitor_log#index'
  get 'visitor_log/:action', controller: 'visitor_log'
  resources :companies
  resources :reasons

  devise_for :users
  resources :employees, path: :persons, except: [:edit] do
    member do
      get 'log_in'
    end
    get 'home/index', as: 'home'
  end

  resources :users, only: [:index, :show, :destroy] do
    collection do
      match 'recently_connected', via: [:post, :get]
      match 'active', via: [:post, :get]
      match 'audit', via: [ :get]
    end
    member do
      get 'require_change_password'
      get 'restore'
      get 'lock'
      get 'unlock'
      put 'change_password'
      put 'change_basic_info'
      put 'attachments'
      post 'image_upload'
      get 'remove_image'
    end


  end


  root to: 'welcome#visitors'

  match '/create_visitor', to: 'welcome#create_visitor', via: [:get, :post]

  get '/update_visitor', to: 'welcome#update_visitor'
  post '/update_visitor_visit', to: 'welcome#update_visitor_visit'
  post '/get_visitor_info', to: 'welcome#get_visitor_info'
  get '/visitors', to: 'welcome#visitors'
  get '/visitor_bye', to: 'welcome#visitor_bye'
  match '/visitor_signout', to: 'welcome#visitor_signout', via: [:get, :post]
  match '/check_visitor', to: 'welcome#check_visitor', via: [:get, :post]
  get '/visitor_sign_form', to: 'welcome#visitor_sign_form'
  get '/visitor_badge', to: 'welcome#visitor_badge'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :admin_login_pages, only: :index do
    collection do
      post :update
    end
  end
end

app/models/reason.rb
# == Schema Information
#
# Table name: reasons
#
#  id         :bigint(8)        not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Reason < ApplicationRecord
end

app/controllers/reasons_controller.rb
class ReasonsController < BaseController
  before_action :set_reason, only: [:show, :edit, :update, :destroy]

  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.all
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
  end

  # GET /reasons/new
  def new
    @reason = Reason.new
  end

  # GET /reasons/1/edit
  def edit
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @reason = Reason.new(reason_params)

    respond_to do |format|
      if @reason.save
        format.html { redirect_to @reason, notice: 'Reason was successfully created.' }
        format.json { render :show, status: :created, location: @reason }
      else
        format.html { render :new }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reasons/1
  # PATCH/PUT /reasons/1.json
  def update
    respond_to do |format|
      if @reason.update(reason_params)
        format.html { redirect_to @reason, notice: 'Reason was successfully updated.' }
        format.json { render :show, status: :ok, location: @reason }
      else
        format.html { render :edit }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason.destroy
    respond_to do |format|
      format.html { redirect_to reasons_url, notice: 'Reason was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reason
      @reason = Reason.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reason_params
      params.require(:reason).permit(:name)
    end
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/views/reasons/_form.html.erb
<%= form_with(model: reason,  local: true, class: 'form-horizontal') do |f| %>
  <% if reason.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reason.errors.count, "error") %> prohibited this reason from being saved:</h2>

      <ul>
      <% reason.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label 'Name', class: 'col-md-2 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group" >
      <div class="col-md-11">
        <%= link_to 'Cancel', reasons_path, class: 'btn btn-warning pull-right' %>
        <%= f.submit 'Save', class: 'btn btn-success pull-right' %>
      </div>
    </div>
<% end %>

app/views/reasons/edit.html.erb
<h1 style="text-align: left">Editing Reason</h1>

<%= render 'form', reason: @reason %>

app/views/reasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reasons</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reasons.each do |reason| %>
      <tr>
        <td><%= reason.name %></td>
        <td><%= link_to 'Show', reason %></td>
        <td><%= link_to 'Edit', edit_reason_path(reason) %></td>
        <td><%= link_to 'Destroy', reason, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reason', new_reason_path %>

app/views/reasons/new.html.erb
<h1 style="text-align: left">New Reason</h1>

<%= render 'form', reason: @reason %>

app/views/reasons/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @reason.name %>
</p>

<%= link_to 'Edit', edit_reason_path(@reason) %> |
<%= link_to 'Back', reasons_path %>